language: objective-c
osx_image: xcode8.2
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
install: true
script:
  - pod lib lint
  - set -o pipefail
  - xcodebuild test -scheme Tyro -configuration Debug | xcpretty -c
  - xcodebuild test -scheme Tyro-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c
  - xcodebuild test -scheme Tyro-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p' | xcpretty -c
  - xcodebuild build -scheme Tyro-watchOS -destination 'platform=watchOS Simulator,name=Apple Watch - 42mm' | xcpretty -c
deploy:
  provider: script
  script: ./scripts/push.sh
  on:
    tags: true
